# Generated by Django 5.2.5 on 2025-09-20 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_alter_description_description'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Description',
        ),
        migrations.AddField(
            model_name='question',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
    ]
