# Generated by Django 5.2.5 on 2025-09-20 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_question_views'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='views',
            new_name='views_count',
        ),
    ]
