# Generated by Django 5.2.5 on 2025-09-22 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_rename_views_question_views_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='is_ready',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='question',
            name='published_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
